repos:
# Official repo for default hooks
- repo: https://github.com/precice/precice-pre-commit-hooks
  rev: 'v3.3'
  hooks:
  - id: format-precice-config
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0
  hooks:
    - id: markdownlint
      exclude: changelog-entries
    - id: markdownlint-fix
      exclude: changelog-entries
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
    - id: shellcheck
      args: [ --external-sources, --exclude=SC1091 ]
