name: Build and run
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-gfortran:
    runs-on: ubuntu-latest
    container: precice/precice:3.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get -qq update
          apt-get -qq install build-essential gfortran
      - name: Build module (gfortran)
        run: |
          make
      - name: Build example
        run: |
          cd examples/solverdummy
          make
      - name: Run example
        run: |
          cd examples/solverdummy
          ./solverdummy precice-config.xml SolverOne &
          PIDOne=$!
          ./solverdummy precice-config.xml SolverTwo &
          PIDTwo=$!
          wait $PIDOne
          wait $PIDTwo
